services:
  - type: web
    name: burn-cash-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python gradio_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
